
services:
  # MongoDB service
  mongo:
    image: mongo:5
    container_name: nest_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # NestJS service
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/nest-backend-assignment?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run start:dev

volumes:
  mongo_data:
